### ISSUE TITLE
Subscribing to ACS Message Event - Failed

### ISSUE THREAD

**Issue by KonstantinLS** [managedcoder/ACSAgentHub#2]
Hi, when finishing deployment, I've got several errors:
![agenthubdeploy2](https://user-images.githubusercontent.com/94699941/142703773-edf6d5b6-7a44-4f73-9ebc-4754d6fcffa0.png)

The error in deploy_log.txt:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (7) Failed to connect to 127.0.0.1 port 4040: Connection refused

**Comment by managedcoder** [comment]
Did you install the prerequisites listed in the README?  One of the prereqs is to install ngrok and you'll need to make sure that the `-ngrokFullPath` argument points to the ngrok.exe in whatever that executable was copied to after installation.

**Comment by managedcoder** [comment]
There was a bug in the README doc that specified $ngrokFullPath when it should have specified -ngrokFullPath and that has now been fixed so I will close this issue but I can reopen it if this was not the issue you were having.

**Comment by managedcoder** [comment]
@KonstantinLS - FYI, the ACS Agent Hub bugs have been fixed and overview and walkthrough videos have been added to README doc

**Comment by mumaheshgit** [comment]
Hi Author, First let me appreciate you for the great work done on this project.  I have the components all up and running in my local except one thing( I am not getting messages from Agent to Bot.). I guess this is because of failure of # Step 6 - Subscribe to ACS Message Event. I did download ngrok as per the instructions. Please let me know what I am missing here?

![image](https://user-images.githubusercontent.com/102542287/193492410-c1951396-a5ed-4d23-b75f-607484c0e47c.png)

**Comment by mumaheshgit** [comment]
Able to properly install ngrok. The application is working fine now. Thanks
